language: java
jdk: 
  - openjdk8
  - openjdk9
dist: trusty

env:
  - COVERAGE=0 TARGET=./monolithic/ui
  - COVERAGE=0 TARGET=./monolithic/service/cart
  - COVERAGE=0 TARGET=./monolithic/service/user
  - COVERAGE=0.3 TARGET=./monolithic/repository/order
  - COVERAGE=0 TARGET=./monolithic/repository/cart
  - COVERAGE=0 TARGET=./monolithic/repository/product
  - COVERAGE=0.3 TARGET=./monolithic/repository/user
  
install:
  - ./gradlew clean jar

after_success:
  - ./gradlew -p $TARGET check

deploy:
  provider: script
  script: echo 'WIP'
  on:
    all_branches: true
